### PR TITLE
Sort tests

### PR DESCRIPTION
**Pull request by mvidner**
https://bugzilla.opensuse.org/show_bug.cgi?id=990267

### CODE REVIEW

**Comment by mvidner** [comment]
An alternative is to use a random but deterministic order, with `rspec --order random ...` which will print out the random seed used and allow reproducing the problem.

But I think such randomization should only be used on a noncritical build path, similarly to what we do with `-Werror` for C/++ packages.

**Comment by mvidner** [comment]
An example of a fix of order-dependent test bug is https://github.com/yast/yast-network/pull/421

**Comment by ancorgs** [comment]
Should we really do this or let the tests fail and fix them one by one? They are not supposed to be order-dependent.

**Comment by ancorgs** [comment]
In other words, I would vote for the alternative proposed in @mvidner's comment.

**Comment by mvidner** [comment]
Now I realize that it should have been debuggable even before, because rake prints out how it calls rspec.

The main problem with the randomized tests is that they tend to break at inopportune moments, and it will put the team in a situation where you are fixing a bug that a colleague made but you can't even tell them "c'mon you should've ran the tests" because they did. And the benefit is IMHO small.

**Comment by jreidinger** [comment]
@mvidner I disagree, as order dependent tests also break when you work locally with given test. And when bootloader failed, I also rerun test with exact order written in travis and see if it can be reproduced. so also :-1: for this change.

**Comment by jreidinger** [comment]
@mvidner @ancorgs so as it is already written out how exactly it is ran, I think alternative is already implemented, so are you OK with closing this PR?

**Comment by mvidner** [comment]
I still disagree and think this PR is valid, but let's close it now and argue when/if the problem appears again.

**Pull request closed without merging**
