### PR TITLE
Fixed typo

### PR DESCRIPTION
**Pull request by mchf**
Build failed in travis due to a typo (see https://travis-ci.org/yast/yast-rake/builds/57637765)

### CODE REVIEW

**Comment by lslezak** [comment]
LGTM, thanks!

**Comment by kobliha** [comment]
Hmm, we usually change all `CONTRIBUTING.md` in all Yast repos. Do you plan to do it everywhere (by a mass-change tool)?

**Comment by lslezak** [comment]
I thought it was already done by @jreidinger globally, but it seems that it was actually added back: https://github.com/yast/yast-rake/commit/9cd10ccbc4c18e2670fbbbe7461aea47eee84acb

**Comment by mchf** [comment]
@kobliha: I didn't see any other repo with the issue so far ... so no ;-)

**Pull request merged**
