### PR TITLE
Update sle12sp2 target

### PR DESCRIPTION
**Pull request by imobachgs**
Update sle12sp2 target to submit to `SUSE:SLE-12-SP2:Update`.

### CODE REVIEW

**Comment by imobachgs** [comment]
Just a question: is `sle12sp2_public` needed? (currently we have a target called `sle12sp1_public`).

**Comment by jreidinger** [comment]
LGTM.
Regarding question - @lslezak should know as I think it is used in jenkins when doing pull request review on public ci.opensuse.org

**Comment by lslezak** [comment]
Yes, the `*_public` projects are needed for the Jenkins jobs running in the public Jenkins instance. IIRC SP2 is not available in OBS yet, but I think we can expect the same naming schema as for the SP1 public repo.

**Comment by jreidinger** [comment]
LGTM, just do not forget that this gem need manual push to rubygems.org and rake osc:sr after it

**Comment by imobachgs** [comment]
Thanks. Ok, I'll take care.

**Pull request merged**
